给 `bot.send` 新增一些 Feature
nonebot/adapter-telegram pull request #31
Opened 2023-05-08 22:11 UTC by lgc2333

- 给 `File` Segment 加入 `filename` 属性，主要作用是当传入 `bytes` 类型文件时也可以指定上传文件名，顺带修了 `bot.send` 发送多个文件时的问题
- 给 `bot.send` 方法新增 `media_group_caption_index` 参数，上传多个 `Document` 类型的文件时有用

#28

2023-05-09 04:41 UTC, j1g5awi requested changes

2023-05-09 04:41 UTC, j1g5awi commented on nonebot/adapters/telegram/message.py
> +        file: Union[str, bytes],
建议是 `file: Union[str, bytes, Tuple[str, bytes]]`, 下同。

2023-05-09 04:45 UTC, j1g5awi commented on nonebot/adapters/telegram/message.py
> +        file: Union[str, bytes],
我想了想，model.py 里的 `InputMedia` 可以改成这樣：

```python
InputFile = Union[bytes, Tuple[str, bytes]]

class InputMedia(BaseModel):
    type: str
    media: Union[InputFile, str]
    caption: Optional[str] = None
    parse_mode: Optional[str] = None
    caption_entities: Optional[List[MessageEntity]] = None
```

最后在 Adapter 的 _call_api 函数里统一处理要发送的文件

2023-05-09 04:56 UTC, j1g5awi commented on nonebot/adapters/telegram/bot.py
> +        media_group_caption_index: int = 0,
```suggestion
        media_group_caption_index: int = 0, # 非 Telegram 原生参数
```

2023-05-10 05:22 UTC, lgc2333 commented
已完成

2023-05-10 11:10 UTC, j1g5awi requested changes

2023-05-10 11:10 UTC, j1g5awi commented on nonebot/adapters/telegram/message.py
> +        )
這裏也需要改。

2023-05-10 11:10 UTC, j1g5awi commented on nonebot/adapters/telegram/adapter.py
> +            files=files,  # type: ignore  # pyright 你 tm 在干什么啊草
...

2023-05-10 11:19 UTC, lgc2333 commented on nonebot/adapters/telegram/adapter.py
> +            files=files,  # type: ignore  # pyright 你 tm 在干什么啊草
(

2023-05-10 11:27 UTC, merged